let score="33abc";
console.log(typeof score);
let inNumber=Number(score);
console.log(typeof inNumber);
console.log( inNumber);
let boolId=0;
let boolConvert=Boolean(boolId);
console.log(boolConvert);
let sumNumber=33;
let stringNumber=String(sumNumber);
console.log(typeof stringNumber);
